/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50:  '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
        },
        dark: {
          bg:      'var(--bg-color)',
          surface: 'var(--card-bg-solid)',
          card:    'var(--card-bg-solid)',
          elevated:'var(--elevated-bg)',
          border:  'var(--border-color)',
          muted:   'var(--muted-text)',
          subtle:  'var(--subtle-border)',
        },
        slate: {
          50:  '#f8fafc',
          100: 'var(--slate-100)',
          200: 'var(--slate-200)',
          300: 'var(--slate-300)',
          400: 'var(--slate-400)',
          500: 'var(--slate-500)',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: 'var(--slate-900)',
        },
        accent: {
          green:  '#10d9a0',
          red:    '#f43f5e',
          amber:  '#f59e0b',
          blue:   '#3b82f6',
          purple: '#a855f7',
          cyan:   '#06b6d4',
        },
      },
      fontFamily: {
        sans:    ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        display: ['Satoshi', 'Geist', 'Plus Jakarta Sans', 'Inter', 'sans-serif'],
        mono:    ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'glow-primary': 'radial-gradient(circle at center, rgba(99,102,241,0.15) 0%, transparent 70%)',
        'glow-green':   'radial-gradient(circle at center, rgba(16,217,160,0.12) 0%, transparent 70%)',
        'glow-red':     'radial-gradient(circle at center, rgba(244,63,94,0.12) 0%, transparent 70%)',
      },
      boxShadow: {
        'glow-sm':  '0 0 20px rgba(99,102,241,0.15)',
        'glow-md':  '0 0 40px rgba(99,102,241,0.2)',
        'glow-lg':  '0 0 60px rgba(99,102,241,0.25)',
        'card':     '0 4px 24px rgba(0,0,0,0.4)',
        'card-hover':'0 8px 40px rgba(0,0,0,0.5)',
        'inner-glow':'inset 0 1px 0 rgba(255,255,255,0.05)',
      },
      animation: {
        'fade-in':    'fadeIn 0.4s ease-out',
        'slide-up':   'slideUp 0.4s ease-out',
        'slide-in':   'slideIn 0.3s ease-out',
        'scale-in':   'scaleIn 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shimmer':    'shimmer 2s linear infinite',
        'float':      'float 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:  { from: { opacity: '0' },                  to: { opacity: '1' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideIn: { from: { opacity: '0', transform: 'translateX(-16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        shimmer: { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        float:   { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
    },
  },
  plugins: [],
}
